#!/usr/bin/env bash
#
# Build tests for LPC1769 (NXP ARM Cortex-M3)
#

# exit on first failure
set -e

#
# Build with the default configurations
#
restore_configs
opt_set MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
exec_test $1 $2 "Default Configuration"

# clean up
restore_configs
